on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

name: Build Artifact
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: oracle
          java-version: 22

      - name: Build with Maven
        run: mvn -B clean package -DskipTests --file pom.xml

      - name: Create run scripts
        run: |
          echo "java --module-path lib --add-modules javafx.controls,javafx.graphics -cp \"arkanoid-1.0.jar:lib/*\" -jar arkanoid-1.0.jar" > target/run-linux.sh
          chmod +x target/run-linux.sh
          echo "java --module-path lib --add-modules javafx.controls,javafx.graphics -cp \"arkanoid-1.0.jar;lib/*\" -jar arkanoid-1.0.jar" > target/run-windows.bat

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: arkanoid-jar
          path: |
            target/*.jar
            target/run-linux.sh
            target/run-windows.bat
            target/lib/
